CREATE PROCEDURE PR
 SQL SECURITY DEFINER
 AS
    DECLARE PROCEDURE NESTED_PR AS
        /*[-unconvertible RS-241716 DECLARE PROCEDURE NESTED_PR_2 AS
        BEGIN

        END]*/

        /*[-unconvertible RS-241716 DECLARE FUNCTION NESTED_F_2
        RETURNS VARCHAR(32765) AS
        BEGIN

        END]*/
    BEGIN

    END
BEGIN

END;