CREATE FUNCTION FUNC
    RETURNS VARCHAR(32765)
    SQL SECURITY DEFINER
    AS
    DECLARE PROCEDURE LOCAL_PROC (PARAM_OUT VARCHAR)
        RETURNS (PARAM_OUT_OUT VARCHAR;
    DECLARE PROCEDURE LOCAL_PROC (PARAM_OUT VARCHAR)
        RETURNS (PARAM_OUT_OUT VARCHAR)
    AS
    BEGIN

		PARAM_OUT_OUT = PARAM_OUT;
		SUSPEND;
    END
BEGIN

END;