CREATE FUNCTION FUNC
    RETURNS VARCHAR(32765)

 SQL SECURITY DEFINER
 AS
    /*DECLARE FUNCTION LOCAL_FUNC RETURNS NUMERIC(34, 8) [-unconvertible RS-239601 PARALLEL_ENABLE];*/
    /*DECLARE FUNCTION LOCAL_FUNC RETURNS NUMERIC(34, 8) [-unconvertible RS-239601 PARALLEL_ENABLE]
        AS
        BEGIN

        END*/
BEGIN

END;