CREATE FUNCTION FUNC
    RETURN VARCHAR2
AS
    FUNCTION LOCAL_FUNC RETURN NUMBER PIPELINED;
    FUNCTION LOCAL_FUNC RETURN NUMBER PIPELINED
        AS
        BEGIN
            NULL;
        END;
BEGIN
    NULL;
END;