CREATE FUNCTION FUNC
    RETURNS VARCHAR(32765)

 SQL SECURITY DEFINER
 AS
    /*DECLARE FUNCTION LOCAL_FUNC RETURNS NUMERIC(34, 8) [-unconvertible RS-239607 PIPELINED];*/
    /*DECLARE FUNCTION LOCAL_FUNC RETURNS NUMERIC(34, 8) [-unconvertible RS-239607 PIPELINED]
        AS
        BEGIN

        END*/
BEGIN

END;