CREATE EXCEPTION CUSTOM_EXCEPTION
	'error';
CREATE EXCEPTION PAST_DUE
	'PAST_DUE EXCEPTION';

CREATE TRIGGER T_Grade_meaning1
    AFTER INSERT
    ON EMPLOYEES
SQL SECURITY DEFINER
AS

    --past_due  EXCEPTION;
BEGIN
    EXCEPTION CUSTOM_EXCEPTION( 'Account past due.');
END;