CREATE EXCEPTION CUSTOM_EXCEPTION
	'error';
CREATE EXCEPTION PAST_DUE
	'PAST_DUE EXCEPTION';


CREATE PROCEDURE calc_annual_sales

 SQL SECURITY DEFINER
 AS
        --past_due  EXCEPTION;
BEGIN
    EXCEPTION CUSTOM_EXCEPTION( 'Account past due.');
END;