CREATE EXCEPTION PAST_DUE
	'PAST_DUE EXCEPTION';
CREATE EXCEPTION CUSTOM_EXCEPTION
	'error';
CREATE OR ALTER PACKAGE errnums

SQL SECURITY DEFINER
AS BEGIN
    --past_due  EXCEPTION;
    PROCEDURE PP_Grade_meaning1;
  END;


RECREATE   PACKAGE BODY errnums
AS BEGIN
    PROCEDURE PP_Grade_meaning1
        AS
    BEGIN
        EXCEPTION CUSTOM_EXCEPTION( 'Account past due.');
    END
END;