CREATE EXCEPTION PAST_DUE
	'PAST_DUE EXCEPTION';
CREATE EXCEPTION CUSTOM_EXCEPTION
	'error';

CREATE FUNCTION test_f
    RETURNS BOOLEAN

 SQL SECURITY DEFINER
 AS
        --past_due  EXCEPTION;
BEGIN
    EXCEPTION CUSTOM_EXCEPTION( 'Account past due.');
RETURN TRUE;
END;