CREATE TRIGGER TRG_DDL
 AFTER ANY DDL STATEMENT
SQL SECURITY DEFINER
AS
     DECLARE system_event VARCHAR(20);
BEGIN
IF (RDB$GET_CONTEXT ('DDL_TRIGGER','EVENT_TYPE') = 'CREATE' OR RDB$GET_CONTEXT ('DDL_TRIGGER','EVENT_TYPE') = 'ALTER' OR RDB$GET_CONTEXT ('DDL_TRIGGER','EVENT_TYPE') = 'DROP') THEN
BEGIN
    system_event = RDB$GET_CONTEXT ('DDL_TRIGGER','OBJECT_TYPE');

END
END;