CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

EXECUTE BLOCK 
 AS 

/*
   DECLARE p1 VARCHAR(100) = 'January 15, 1989, 11:00 A.M.';
   DECLARE p2 TIMESTAMP = date '2020-10-25';
   DECLARE p3 TIMESTAMP WITH TIME ZONE = CURRENT_TIMESTAMP;
   DECLARE res TIMESTAMP;
*/
BEGIN
/*
  select [-unconvertible RS-245838 CAST(:p1 AS TIMESTAMP [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS TIMESTAMP, 'Month dd, YYYY, HH:MI A.M.')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS TIMESTAMP, 'Month dd, YYYY, HH:MI A.M.', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS TIMESTAMP [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'Month dd, YYYY, HH:MI A.M.', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select [-unconvertible RS-245838 CAST(:p2 AS TIMESTAMP)
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p2 AS TIMESTAMP [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p2 AS TIMESTAMP, 'YYYY-MM-DD')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p2 AS TIMESTAMP, 'YYYY-MM-DD', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;  
  select [-unconvertible RS-245838 CAST(:p2 AS TIMESTAMP [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'YYYY-MM-DD', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select [-unconvertible RS-245838 CAST(:p3 AS TIMESTAMP)
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p3 AS TIMESTAMP [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p3 AS TIMESTAMP, 'DD.MM.YY HH24:MI:SSXFF9TZR')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p3 AS TIMESTAMP, 'DD.MM.YY HH24:MI:SSXFF9TZR', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;  
  select [-unconvertible RS-245838 CAST(:p3 AS TIMESTAMP [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'DD.MM.YY HH24:MI:SSXFF9TZR', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND; 
*/
END;


EXECUTE BLOCK 
 AS 

/*
   DECLARE p4 [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] = timestamp '2020-10-25 02:30:00+02:00';
   DECLARE res TIMESTAMP;
*/
BEGIN
/*
  select [-unconvertible RS-245838 CAST(:p4 AS TIMESTAMP)
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p4 AS TIMESTAMP [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p4 AS TIMESTAMP, 'DD.MM.YY HH24:MI:SSXFF9TZR')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p4 AS TIMESTAMP, 'DD.MM.YY HH24:MI:SSXFF9TZR', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;  
  select [-unconvertible RS-245838 CAST(:p4 AS TIMESTAMP [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'DD.MM.YY HH24:MI:SSXFF9TZR', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
*/
END;