CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

/*EXECUTE BLOCK 
 AS 

   DECLARE p1 VARCHAR(100) = '22-OCT-1997';
   DECLARE p2 TIMESTAMP = date '2020-10-25';
   DECLARE p3 TIMESTAMP = timestamp '2020-10-25 02:30:00';
   DECLARE p4 TIMESTAMP WITH TIME ZONE = timestamp '2020-10-25 02:30:00+02:00';
   DECLARE res [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE];
BEGIN
  select [-unconvertible RS-245838 CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'DD-Mon-YYYY')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'DD-Mon-YYYY', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'DD-Mon-YYYY', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select [-unconvertible RS-245838 CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'YYYY-MM-DD')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'YYYY-MM-DD', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;  
  select [-unconvertible RS-245838 CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'YYYY-MM-DD', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select [-unconvertible RS-245838 CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'DD.MM.YY HH24:MI:SSXFF9')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'DD.MM.YY HH24:MI:SSXFF9', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;  
  select [-unconvertible RS-245838 CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'DD.MM.YY HH24:MI:SSXFF9', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND; 

  select [-unconvertible RS-245838 CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR])
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'DD.MM.YY HH24:MI:SSXFF9TZR')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select [-unconvertible RS-245838 CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE], 'DD.MM.YY HH24:MI:SSXFF9TZR', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;  
  select [-unconvertible RS-245838 CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] [-unconvertible RS-245838 [-unconvertible RS-245741 DEFAULT NULL ON CONVERSION ERROR]], 'DD.MM.YY HH24:MI:SSXFF9TZR', 'NLS_DATE_LANGUAGE = AMERICAN')
  ]from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
END;*/