CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

/*EXECUTE BLOCK
 AS

   DECLARE p1 VARCHAR(100) = '22-OCT-1997';
   DECLARE p2 TIMESTAMP = date '2020-10-25';
   DECLARE p3 TIMESTAMP = timestamp '2020-10-25 02:30:00';
   DECLARE p4 TIMESTAMP WITH TIME ZONE = timestamp '2020-10-25 02:30:00+02:00';
   DECLARE res [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE];
BEGIN
  select CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE FORMAT 'DD-Mon-YYYY'] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE FORMAT 'DD-Mon-YYYY']  )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] FORMAT 'DD-Mon-YYYY'   )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE]  )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE]   )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE]  )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p3 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE]   )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE])
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE]  )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p4 AS [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE]   )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
END;*/