CREATE PROCEDURE PROCEDURE_NAME(out_p  VARCHAR)
  RETURNS( OUT_P_OUT VARCHAR)
 SQL SECURITY DEFINER
 AS
BEGIN

OUT_P_OUT = OUT_P;
  SUSPEND;
END;

CREATE TRIGGER CALLING_TRIGGER_NAME
BEFORE INSERT ON EMPLOYEES
SQL SECURITY DEFINER
AS
     DECLARE out_value VARCHAR(50);
BEGIN
    out_value = 'out_value';
    EXECUTE PROCEDURE PROCEDURE_NAME(:out_value);
END;