CREATE PROCEDURE PROCEDURE_NAME(out_p OUT VARCHAR)
IS
BEGIN
    NULL;
END;

CREATE PROCEDURE CALLING_PROCEDURE_NAME
    IS
    out_value VARCHAR2(50);
BEGIN
    out_value := 'out_value';
    PROCEDURE_NAME(out_value);
END;