CREATE PROCEDURE PROCEDURE_NAME
 SQL SECURITY DEFINER
 AS BEGIN

END;

CREATE FUNCTION FUNCTION_NAME
RETURNS VARCHAR(32765)
     SQL SECURITY DEFINER
 AS
BEGIN
    EXECUTE PROCEDURE PROCEDURE_NAME;
    EXECUTE PROCEDURE PROCEDURE_NAME();
END;