CREATE EXCEPTION CUSTOM_EXCEPTION 'error';

CREATE FUNCTION F_Null_In_Exception
RETURNS VARCHAR(32765)
SQL SECURITY DEFINER
AS
BEGIN
  EXCEPTION CUSTOM_EXCEPTION( 'Неправильный номер');
  RETURN '';
  /*EXCEPTION*/
  WHEN ANY DO BEGIN
  END
END;