CREATE EXCEPTION CUSTOM_EXCEPTION 'error';

CREATE TRIGGER T_Null_In_Exception
BEFORE INSERT ON EMPLOYEES
SQL SECURITY DEFINER
AS
BEGIN
  EXCEPTION CUSTOM_EXCEPTION( 'Invalid number');
  /*EXCEPTION*/
  WHEN ANY DO BEGIN
  END
END;