CREATE TRIGGER T_Grade_meaning1
    AFTER INSERT
    ON EMPLOYEES
SQL SECURITY DEFINER
AS

    DECLARE CURSOR_NAME  ;
    DECLARE CURSOR_NAME CURSOR FOR
        (SELECT FIRST_NAME FROM EMPLOYEES);
BEGIN

END;