-- инициализация внутри PACKAGE и объявление внутри PACKAGE BODY
/*CREATE PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN
    [-unconvertible RS-233552 DECLARE BOOKS_CUR  ;]
END;*/


/*CREATE PACKAGE BODY BOOK_INFO
AS BEGIN
    [-unconvertible RS-233552 DECLARE BOOKS_CUR

    CURSOR FOR
    (SELECT *
    FROM BOOKS);]
END;*/


-- инициализация и объявление внутри PACKAGE BODY
CREATE PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN

END;

/*RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    [-unconvertible RS-233552 DECLARE BOOKS_CUR  ;]
    [-unconvertible RS-233552 DECLARE BOOKS_CUR

        CURSOR FOR
    (SELECT *
    FROM BOOKS);]
END;*/

-- инициализация и объявление внутри PACKAGE
/*CREATE OR ALTER PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN
    [-unconvertible RS-233552 DECLARE BOOKS_CUR  ;]
    [-unconvertible RS-233552 DECLARE BOOKS_CUR

            CURSOR FOR
    (SELECT *
    FROM BOOKS);]
END;*/


CREATE PACKAGE BODY BOOK_INFO
AS BEGIN

END;

-- объявление и инициализация в функции внутри пакета

CREATE OR ALTER PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN
    FUNCTION TEST_F RETURNS BOOLEAN;
END;

RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    FUNCTION TEST_F
        RETURNS BOOLEAN
    AS
        DECLARE BOOKS_CUR  ;
        DECLARE BOOKS_CUR

            CURSOR FOR
            (SELECT *
            FROM BOOKS);
    BEGIN

    RETURN TRUE;
    END
END;