CREATE OR ALTER PROCEDURE LOC_VAR

 SQL SECURITY DEFINER
 AS
     DECLARE var_ NUMERIC(34, 8) = 5;
BEGIN
    IF (TRUE) THEN
    BEGIN
        var_ = :var_ /0;
    END
/*EXCEPTION*/
    WHEN GDSCODE EXCEPTION_INTEGER_DIVIDE_BY_ZERO, GDSCODE EXCEPTION_FLOAT_DIVIDE_BY_ZERO DO
        BEGIN

        END
END;