CREATE EXCEPTION USER_EXCEPTION
	'USER_EXCEPTION EXCEPTION';

CREATE OR ALTER PROCEDURE LOC_VAR
 SQL SECURITY DEFINER
 AS
    --user_exception exception;
BEGIN
    IF (TRUE) THEN
    BEGIN
        EXCEPTION user_exception;
    END
/*EXCEPTION*/
    WHEN EXCEPTION USER_EXCEPTION DO
        BEGIN

        END
END;