CREATE EXCEPTION USER_EXCEPTION
	'USER_EXCEPTION EXCEPTION';
CREATE EXCEPTION USER_EXCEPTION_2
	'USER_EXCEPTION_2 EXCEPTION';

CREATE OR ALTER PROCEDURE LOC_VAR
 SQL SECURITY DEFINER
 AS
    --user_exception exception;
    --user_exception_2 exception;
BEGIN
    IF (TRUE) THEN
    BEGIN
        EXCEPTION user_exception_2;
    END
/*EXCEPTION*/
    WHEN EXCEPTION USER_EXCEPTION , EXCEPTION USER_EXCEPTION_2 DO
        BEGIN

        END
END;