package ru.redsoft.ora2rdb;

public enum BlockType {
    UNKNOWN,
    FUNCTION_AND_PROCEDURE,
    TRIGGER,
    SIMPLE_COMMAND,
    SIMPLE_COMMAND_INSIDE_PACKAGE,
    PACKAGE,
    TYPE_BODY,
    ANONYMOUS_BLOCK,
    WITH_SELECT_WITH_DECLARATION
}
