CREATE PROCEDURE PROCEDURE_NAME(in_p VARCHAR)
 SQL SECURITY DEFINER
 AS
BEGIN

END;


CREATE PACKAGE CALLING_PACKAGE
 SQL SECURITY DEFINER
AS BEGIN
   FUNCTION CALLING_FUNCTION RETURNS NUMERIC(34, 8);
   PROCEDURE CALLING_PROCEDURE;
  END ;


CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
   FUNCTION CALLING_FUNCTION
   RETURNS NUMERIC(34, 8)
   AS
         DECLARE record_variable pkg.my_record;
    BEGIN
         EXECUTE PROCEDURE PROCEDURE_NAME(:record_variable);   -- call procedure
    END

   PROCEDURE CALLING_PROCEDURE
    AS
         DECLARE record_variable pkg.my_record;
    BEGIN
        EXECUTE PROCEDURE PROCEDURE_NAME(:record_variable);   -- call procedure
    END

  END ;