INSERT INTO COUNTRY
(COUNTRY, CURRENCY)
VALUES
    ( 'RUSSIA', 'RUBLE')
    RETURNING COUNTRY, CURRENCY INTO :BIND2 , :BIND1;
-- the keyword RETURN is allowed
INSERT INTO COUNTRY
(COUNTRY, CURRENCY)
VALUES
    ( 'RUSSIA', 'RUBLE')
    RETURNING COUNTRY, CURRENCY INTO :BIND2 , :BIND1;