--L_EMPLOYEES EMPLOYEE_AAT
CREATE GLOBAL TEMPORARY TABLE L_EMPLOYEES (
	K INTEGER,
	VAL TYPE OF COLUMN employees.employee_id,
	CONSTRAINT PK_L_EMPLOYEES PRIMARY KEY (K)
);

--L_EMPLOYEE_INDICES BOOLEAN_AAT
CREATE GLOBAL TEMPORARY TABLE L_EMPLOYEE_INDICES (
	K INTEGER,
	VAL BOOLEAN,
	CONSTRAINT PK_L_EMPLOYEE_INDICES PRIMARY KEY (K)
);


EXECUTE BLOCK
 AS

/*
   --TYPE employee_aat IS TABLE OF TYPE OF COLUMN employees.employee_id INDEX BY INTEGER;

   --l_employees employee_aat;

   --TYPE boolean_aat IS TABLE OF BOOLEAN INDEX BY INTEGER;

   --l_employee_indices boolean_aat;
*/
BEGIN
/*
   UPDATE OR INSERT INTO L_EMPLOYEES VALUES (1, 7839);
   UPDATE OR INSERT INTO L_EMPLOYEES VALUES (100, 7654);
   UPDATE OR INSERT INTO L_EMPLOYEES VALUES (500, 7950);
   --
   UPDATE OR INSERT INTO L_EMPLOYEE_INDICES VALUES (1, TRUE);
   UPDATE OR INSERT INTO L_EMPLOYEE_INDICES VALUES (500, TRUE);
   UPDATE OR INSERT INTO L_EMPLOYEE_INDICES VALUES (799, TRUE);
   --
   [-unconvertible RS-240654 FORALL l_index IN INDICES OF l_employee_indices
      BETWEEN 1 AND 500
        UPDATE employees
        SET salary = 10000
        WHERE employee_id = (SELECT VAL FROM L_EMPLOYEES WHERE K = l_index)];
*/
END;