SELECT WIDTH_BUCKET(40, 0, 100, 5) FROM RDB$DATABASE;
SELECT WIDTH_BUCKET(3.7, 1, 9, 3) FROM RDB$DATABASE;

SELECT WIDTH_BUCKET(-3.7, 1, 9, 3) FROM RDB$DATABASE;
SELECT WIDTH_BUCKET(37, 1, 9, 3) FROM RDB$DATABASE;

SELECT WIDTH_BUCKET(-3.7, -9, -1, 3) FROM RDB$DATABASE;