--L_EMPLOYEES EMPLOYEE_AAT
CREATE GLOBAL TEMPORARY TABLE L_EMPLOYEES (
	K INTEGER,
	VAL TYPE OF COLUMN employees.employee_id,
	CONSTRAINT PK_L_EMPLOYEES PRIMARY KEY (K)
);

--L_EMPLOYEE_INDICES INDICES_AAT
CREATE GLOBAL TEMPORARY TABLE L_EMPLOYEE_INDICES (
	K INTEGER,
	VAL INTEGER,
	CONSTRAINT PK_L_EMPLOYEE_INDICES PRIMARY KEY (K)
);


EXECUTE BLOCK
 AS

/*
    --TYPE employee_aat IS TABLE OF TYPE OF COLUMN employees.employee_id INDEX BY INTEGER;

   --l_employees employee_aat;

   --TYPE indices_aat IS TABLE OF INTEGER INDEX BY INTEGER;

   --l_employee_indices indices_aat;
*/
BEGIN
/*
   UPDATE OR INSERT INTO L_EMPLOYEES VALUES (-77, 7820);
   UPDATE OR INSERT INTO L_EMPLOYEES VALUES (13067, 7799);
   UPDATE OR INSERT INTO L_EMPLOYEES VALUES (99999999, 7369);
   --
   UPDATE OR INSERT INTO L_EMPLOYEE_INDICES VALUES (100, -77);
   UPDATE OR INSERT INTO L_EMPLOYEE_INDICES VALUES (200, 99999999);
   --
   [-unconvertible RS-240654 FORALL l_index IN VALUES OF l_employee_indices
        UPDATE employees
        SET salary = 10000
        WHERE employee_id = (SELECT VAL FROM L_EMPLOYEES WHERE K = l_index)];
*/
END;