/*CREATE [-unconvertible RS-243395 SHARDED] TABLE Customers(
    CustNo      NUMERIC(34, 8) NOT NULL,
    Name        VARCHAR(50)
)
[-unconvertible RS-243394 PARTITION BY CONSISTENT HASH (CustNo)
PARTITIONS AUTO
TABLESPACE SET ts1];*/