CREATE PROCEDURE PROCEDURE_NAME
     SQL SECURITY DEFINER
 AS
     DECLARE out_value  VARCHAR(20) = 'value';
    DECLARE PROCEDURE NESTED_PROCEDURE_NAME(in_param   VARCHAR)
          RETURNS( IN_PARAM_OUT VARCHAR)

AS
    BEGIN

    IN_PARAM_OUT = IN_PARAM;
SUSPEND;
END

BEGIN
    SELECT IN_PARAM_OUT  FROM NESTED_PROCEDURE_NAME(:out_value) INTO out_value; -- 1
    PROCEDURE_NAME.NESTED_PROCEDURE_NAME(:out_value); -- 2
END;