CREATE PACKAGE PACKAGE_NAME IS
       PROCEDURE PROCEDURE_NAME_WITH_IN_PARAMETER (in_p VARCHAR);
       PROCEDURE PROCEDURE_NAME_WITHOUT_PARAMETER ;
       PROCEDURE PROCEDURE_NAME_WITH_OUT_PARAMETER (in_p OUT VARCHAR);
END;

CREATE PACKAGE BODY PACKAGE_NAME
    IS
    PROCEDURE PROCEDURE_NAME_WITH_IN_PARAMETER (in_p VARCHAR)
    IS
    BEGIN
        NULL;
    END;

    PROCEDURE PROCEDURE_NAME_WITHOUT_PARAMETER
    IS
    BEGIN
        NULL;
    END;

    PROCEDURE PROCEDURE_NAME_WITH_OUT_PARAMETER (in_p OUT VARCHAR)
    IS
    BEGIN
        NULL;
    END;
END;

CREATE PROCEDURE PROCEDURE_NAME
    IS
    out_value VARCHAR2(50);
    in_value VARCHAR2(50);
BEGIN
    PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(out_value); -- out param

    PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(in_value); -- in param

    PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER(); -- without param

    PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

END;