


CREATE PACKAGE PACKAGE_NAME  SQL SECURITY DEFINER
AS BEGIN
       PROCEDURE PROCEDURE_NAME_WITH_IN_PARAMETER (in_p VARCHAR);
       PROCEDURE PROCEDURE_NAME_WITHOUT_PARAMETER ;
       PROCEDURE PROCEDURE_NAME_WITH_OUT_PARAMETER (in_p  VARCHAR);
  END;



CREATE PACKAGE BODY PACKAGE_NAME
    AS BEGIN
    PROCEDURE PROCEDURE_NAME_WITH_IN_PARAMETER (in_p VARCHAR)
    AS
    BEGIN

    END

    PROCEDURE PROCEDURE_NAME_WITHOUT_PARAMETER
    AS
    BEGIN

    END

    PROCEDURE PROCEDURE_NAME_WITH_OUT_PARAMETER (in_p  VARCHAR)
          RETURNS( IN_P_OUT VARCHAR)

AS
    BEGIN

    IN_P_OUT = IN_P;
SUSPEND;
END
  END;


CREATE PACKAGE CALLING_PACKAGE_NAME
 SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME RETURNS VARCHAR(32765);

   PROCEDURE PROCEDURE_NAME;
  END ;


RECREATE   PACKAGE BODY CALLING_PACKAGE_NAME
AS BEGIN
   FUNCTION FUNCTION_NAME
   RETURNS VARCHAR(32765)
   AS
     DECLARE out_value VARCHAR(50);
     DECLARE in_value VARCHAR(50);
BEGIN
    SELECT IN_P_OUT  FROM PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(:out_value) INTO out_value; -- out param

    EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(:in_value); -- in param

    PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER(); -- without param

    EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

END

   PROCEDURE PROCEDURE_NAME
    AS
         DECLARE out_value VARCHAR(50);
         DECLARE in_value VARCHAR(50);
    BEGIN
        SELECT IN_P_OUT  FROM PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(:out_value) INTO out_value; -- out param

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(:in_value); -- in param

        PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER(); -- without param

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param
    END

  END ;