CREATE PROCEDURE PROCEDURE_NAME(in_p VARCHAR)
 SQL SECURITY DEFINER
 AS
BEGIN

END;

CREATE FUNCTION CALLING_FUNCTION
RETURNS NUMERIC(34, 8)
     SQL SECURITY DEFINER
 AS
     DECLARE cursor_variable pkg.cursor_type;
BEGIN
    EXECUTE PROCEDURE PROCEDURE_NAME(:cursor_variable); -- call procedure
END;