CREATE PROCEDURE PROCEDURE_NAME(in_p VARCHAR)
 SQL SECURITY DEFINER
 AS
BEGIN

END;

CREATE TRIGGER TRIGGER_NAME
BEFORE INSERT ON EMPLOYEES SQL SECURITY DEFINER
AS

     DECLARE cursor_variable pkg.cursor_type;
BEGIN
     EXECUTE PROCEDURE PROCEDURE_NAME(:cursor_variable); -- call procedure
END;