CREATE PROCEDURE PROCEDURE_NAME(in_p VARCHAR)
IS
BEGIN
    NULL;
END;

CREATE TRIGGER TRIGGER_NAME
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
    cursor_variable pkg.cursor_type;
BEGIN
     PROCEDURE_NAME(cursor_variable); -- call procedure
END;