CREATE PROCEDURE PROCEDURE_NAME(in_p VARCHAR)
 SQL SECURITY DEFINER
 AS
BEGIN

END;

CREATE PROCEDURE CALLING_PROCEDURE
     SQL SECURITY DEFINER
 AS
     DECLARE cursor_variable pkg.cursor_type;
BEGIN
    EXECUTE PROCEDURE PROCEDURE_NAME(:cursor_variable); -- call procedure
END;