CREATE PACKAGE PackF_Null_In_For
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Null_In_For
   RETURNS VARCHAR(32765);
  END;

CREATE PACKAGE BODY PackF_Null_In_For
AS BEGIN
   FUNCTION PF_Null_In_For
   RETURNS VARCHAR(32765)
   AS
    DECLARE VARIABLE i INTEGER;
    BEGIN
     i = 1;
     WHILE ( i <= 3) DO
     BEGIN

     i = i + 1;
     END
     RETURN '';
   END
END;