


/*CREATE PACKAGE BOOK_INFO

SQL SECURITY DEFINER
AS BEGIN
    [-unconvertible RS-233552 DECLARE cur CURSOR FOR
    (SELECT * FROM employees);]
     DECLARE VARIABLE cur_rec TYPE OF TABLE cur;
  END;*/



CREATE PACKAGE BODY BOOK_INFO
AS BEGIN

  END;


/*CREATE OR ALTER PACKAGE BOOK_INFO

SQL SECURITY DEFINER
AS BEGIN
    [-unconvertible RS-233552 DECLARE cur CURSOR FOR
(SELECT * FROM employees);]

  END;*/



RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    CONSTANT cur_rec TYPE OF TABLE cur;
  END;


CREATE OR ALTER PACKAGE BOOK_INFO

SQL SECURITY DEFINER
AS BEGIN

  END;



RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    DECLARE cur CURSOR FOR
(SELECT * FROM employees);
CONSTANT cur_rec TYPE OF TABLE cur;
  END;


CREATE OR ALTER PACKAGE BOOK_INFO

SQL SECURITY DEFINER
AS BEGIN
    FUNCTION TEST_F RETURNS BOOLEAN;
  END;



RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    FUNCTION TEST_F
    RETURNS BOOLEAN
    AS
        DECLARE CUR CURSOR FOR
            (SELECT * FROM EMPLOYEES);
         DECLARE VARIABLE CUR_REC TYPE OF TABLE CUR;
    BEGIN

        RETURN TRUE;
    END

  END;