-- Объявление внутри заголовка пакета
/*CREATE PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN
    [-unconvertible RS-233552 DECLARE cur CURSOR FOR
    (SELECT * FROM employees);]
     DECLARE VARIABLE [-unconvertible RS-246002 cur_rec TYPE OF TABLE cur;]
END;*/


CREATE PACKAGE BODY BOOK_INFO
AS BEGIN

END;
-- Объявление курсора в заголовке пакета , а переменной внутри тела пакета
/*CREATE OR ALTER PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN
    [-unconvertible RS-233552 DECLARE cur CURSOR FOR
(SELECT * FROM employees);]

END;*/


/*RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
     DECLARE VARIABLE [-unconvertible RS-246002 cur_rec TYPE OF TABLE cur;]
END;*/


-- Объявление курсора и переменной в теле пакета
CREATE OR ALTER PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN

END;

/*RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    [-unconvertible RS-233552 DECLARE cur CURSOR FOR
(SELECT * FROM employees);]
 DECLARE VARIABLE [-unconvertible RS-246002 cur_rec TYPE OF TABLE cur;]
END;*/

-- Объявление в функции в пакете
CREATE OR ALTER PACKAGE BOOK_INFO
 SQL SECURITY DEFINER
AS BEGIN
    FUNCTION TEST_F RETURNS BOOLEAN;
END;

RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    FUNCTION TEST_F
    RETURNS BOOLEAN
    AS
        DECLARE CUR CURSOR FOR
            (SELECT * FROM EMPLOYEES);
         DECLARE VARIABLE CUR_REC TYPE OF TABLE CUR;
    BEGIN

        RETURN TRUE;
    END

END;