  CREATE TABLE "COUNTRIES_DEMO" (
    "COUNTRY_ID" CHAR(2 ) CONSTRAINT "COUNTRY_ID_NN_DEMO" NOT NULL ,
	"COUNTRY_NAME" VARCHAR(40 ), 
	"CURRENCY_NAME" VARCHAR(25 ), 
	"CURRENCY_SYMBOL" VARCHAR(3 ), 
	"REGION" VARCHAR(15 ), 
	 CONSTRAINT "COUNTRY_C_ID_PK_DEMO" PRIMARY KEY ("COUNTRY_ID") 
  );