CREATE OR ALTER PACKAGE MY_TYPES SQL SECURITY CURRENT_USER AS BEGIN
    --TYPE MY_AA IS TABLE OF VARCHAR(20) INDEX BY INTEGER;
    FUNCTION INIT_MY_AA RETURNS MY_AA;
  END;


RECREATE   PACKAGE BODY MY_TYPES AS BEGIN
    FUNCTION INIT_MY_AA RETURNS MY_AA AS
         DECLARE RET MY_AA;
    BEGIN
        RETURN RET;
    END
  END;