--SALARIES SALARYMAP
CREATE GLOBAL TEMPORARY TABLE SALARIES (
	K VARCHAR(100),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_SALARIES PRIMARY KEY (K)
);


EXECUTE BLOCK
 AS

/*
--TYPE SalaryMap IS TABLE OF NUMERIC(34, 8) INDEX BY VARCHAR(100);

    --salaries SalaryMap = [-unconvertible RS-239362 SalaryMap('John' => 50000, 'Alice' => 60000, 'Bob' => 55000)];
*/
BEGIN
/*

*/
END;