--CITY_POPULATION POPULATION
CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION PRIMARY KEY (K)
);


EXECUTE BLOCK
 AS


--TYPE POPULATION IS TABLE OF NUMERIC(34, 8)
    INDEX BY VARCHAR(64);

    --CITY_POPULATION  POPULATION;

BEGIN

END;