--CITY_POPULATION POPULATION
CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION PRIMARY KEY (K)
);


EXECUTE BLOCK
 AS


--TYPE POPULATION IS TABLE OF NUMERIC(34, 8)
    INDEX BY VARCHAR(64);

    --CITY_POPULATION  POPULATION;
     DECLARE I  VARCHAR(64);
     DECLARE VAL NUMERIC(34, 8);

BEGIN
    VAL = (SELECT VAL FROM CITY_POPULATION WHERE K = :I);

    I = (SELECT FIRST 1 K FROM CITY_POPULATION ORDER BY K DESC);
    I = (SELECT FIRST 1 K FROM CITY_POPULATION ORDER BY K ASC);
    I = (SELECT FIRST 1 K FROM CITY_POPULATION WHERE K > :I ORDER BY K ASC);
    I = (SELECT COUNT(*) FROM CITY_POPULATION);
    I = (SELECT FIRST 1 K FROM CITY_POPULATION WHERE K < 'MIDLAND' ORDER BY K DESC);
    bool_val = (SELECT COUNT(*) > 0 FROM CITY_POPULATION WHERE K = 'MIDLAND');
    DELETE FROM CITY_POPULATION WHERE K = 'MIDLAND';
END;