
CREATE PROCEDURE PROCEDURE_NAME(out_p  VARCHAR)
  RETURNS( OUT_P_OUT VARCHAR)

 SQL SECURITY DEFINER
 AS
BEGIN


OUT_P_OUT = OUT_P;
  SUSPEND;
END;


CREATE PACKAGE CALLING_PACKAGE
 SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURNS VARCHAR(32765);
  END ;


CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURNS VARCHAR(32765)
   AS
         DECLARE out_value VARCHAR(50);
    BEGIN
        out_value = 'out_value';
        SELECT OUT_P_OUT  FROM PROCEDURE_NAME(:out_value) INTO out_value;
    END
  END ;

CREATE PACKAGE CALLING_PACKAGE
 SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
  END ;


CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    AS
         DECLARE out_value VARCHAR(50);
    BEGIN
        out_value = 'out_value';
        SELECT OUT_P_OUT  FROM PROCEDURE_NAME(:out_value) INTO out_value;
    END
  END ;