
CREATE PROCEDURE PROCEDURE_NAME(out_p  VARCHAR)
  RETURNS( OUT_P_OUT VARCHAR)

 SQL SECURITY DEFINER
 AS
BEGIN


OUT_P_OUT = OUT_P;
  SUSPEND;
END;

CREATE PROCEDURE CALLING_PROCEDURE_NAME
     SQL SECURITY DEFINER
 AS
     DECLARE out_value VARCHAR(50);
BEGIN
    out_value = 'out_value';
    SELECT OUT_P_OUT  FROM PROCEDURE_NAME(:out_value) INTO out_value;
END;