CREATE EXCEPTION INVALID_COMPANY_ID
	'INVALID_COMPANY_ID EXCEPTION';

CREATE TRIGGER T_Grade_meaning1
    AFTER INSERT
    ON EMPLOYEES
SQL SECURITY DEFINER
AS

    --invalid_company_id EXCEPTION;
BEGIN

END;