CREATE EXCEPTION E_NOT_FOUND2
	'E_NOT_FOUND2 EXCEPTION';
CREATE EXCEPTION E_NOT_FOUND
	'E_NOT_FOUND EXCEPTION';
/*CREATE OR ALTER PACKAGE PACKAGE_NAME  SQL SECURITY DEFINER
AS BEGIN 

    --[-unconvertible RS-245963 e_not_found EXCEPTION;]  
    --[-unconvertible RS-245963 e_not_found2 EXCEPTION;]  

  END ;*/