/*CREATE OR ALTER PACKAGE PACKAGE_NAME  SQL SECURITY DEFINER
AS BEGIN 

    [-unconvertible RS-239691 TYPE t_cursor IS REF CURSOR;]  

    [-unconvertible RS-239691 TYPE t_cursor_return IS REF CURSOR RETURN TYPE OF TABLE employees;]  

END ;*/