/*CREATE OR ALTER PACKAGE PACKAGE_NAME
SQL SECURITY DEFINER
AS BEGIN 

    [-unconvertible RS-197284 SUBTYPE subtype_age IS INTEGER RANGE 18 .. 65 NOT NULL;]  

    [-unconvertible RS-197284 SUBTYPE subtype_emp_name IS VARCHAR(100);]  

END ;*/