CREATE OR ALTER FUNCTION CALL_F
RETURNS BOOLEAN
 SQL SECURITY DEFINER
 AS
     DECLARE EMP_NAME VARCHAR(50);
     DECLARE EMP_SALARY NUMERIC(34, 8);
BEGIN
    EXECUTE STATEMENT ('SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 142')
     INTO :EMP_NAME, :EMP_SALARY;
    RETURN TRUE;
END;