CREATE OR ALTER PACKAGE Pack_Grade_meaning1
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Grade_meaning1 (degree INT128)
   RETURNS BOOLEAN;
   PROCEDURE PP_Grade_meaning1;
END;

RECREATE PACKAGE BODY Pack_Grade_meaning1
AS BEGIN
    FUNCTION PF_Grade_meaning1 (degree INT128)
    RETURNS BOOLEAN
    AS

  DECLARE VARIABLE ITEM_TEMP_CURSOR CURSOR FOR (SELECT LAST_NAME, EMP_NO
                FROM EMPLOYEE);

  DECLARE VARIABLE ITEM TYPE OF TABLE ITEM_TEMP_CURSOR;
BEGIN
        FOR (
                SELECT LAST_NAME, EMP_NO
                FROM EMPLOYEE
              ) INTO ITEM DO
        BEGIN


        END
        RETURN TRUE;
    END

    PROCEDURE PP_Grade_meaning1
    AS

  DECLARE VARIABLE ITEM_TEMP_CURSOR CURSOR FOR (SELECT LAST_NAME, EMP_NO
                    FROM EMPLOYEE);

  DECLARE VARIABLE ITEM TYPE OF TABLE ITEM_TEMP_CURSOR;
BEGIN
        FOR (
                    SELECT LAST_NAME, EMP_NO
                    FROM EMPLOYEE
                  ) INTO ITEM DO
        BEGIN

        END
  END
END;