
EXECUTE BLOCK
 AS

/*
    [-unconvertible RS-239343 TYPE FOURSOME IS VARRAY(4) OF VARCHAR(15);]

    [-unconvertible RS-239343 TEAM FOURSOME] = [-unconvertible RS-239379 FOURSOME('JOHN', 'MARY', 'ALBERTO', 'JUANITA')];
     DECLARE NUMELEMENTS INT128;
     DECLARE ELEMENTEXISTS BOOLEAN;
     DECLARE FIRSTELEMENT VARCHAR(100);
     DECLARE LASTELEMENT VARCHAR(100);
     DECLARE LIMITVAR VARCHAR(100);
     DECLARE I NUMERIC(34, 8);
*/
BEGIN
/*
    NUMELEMENTS = TEAM.COUNT;
    -- EXTEND
    TEAM.EXTEND; -- Increases collection size (can be removed during conversion)
    -- GET ELEMENT BY ID (2)
    FIRSTELEMENT = TEAM(2);
    -- ACCESS THE FIRST ELEMENT OF THE VARRAY DIRECTLY USING INDEX 1
    FIRSTELEMENT = TEAM(TEAM.FIRST);
    -- ACCESS THE LAST ELEMENT OF THE VARRAY USING THE COUNT METHOD TO DETERMINE THE NUMBER OF ELEMENTS
    LASTELEMENT = TEAM(TEAM.LAST);
    -- DELETE (DELETE ALL ELEMENTS FROM VARRAY)
    TEAM.DELETE();
    -- DELETE LAST ELEMENT OF VARRAY
    TEAM.TRIM;
    -- TRIM(N) - DELETE LAST N ELEMENTS OF VARRAY
    TEAM.TRIM(2);
    -- ONLY VARRAY HAVE LIMIT
    LIMITVAR = TEAM.LIMIT;
    -- EXISTS IS A FUNCTION THAT TELLS YOU WHETHER THE SPECIFIED ELEMENT OF A VARRAY OR NESTED TABLE EXISTS.
    ELEMENTEXISTS = TEAM.EXISTS(2); -- Checks if second element exists
    I = TEAM.NEXT; -- Returns next element index
    I = TEAM.PRIOR; -- Returns previous element index
*/
END;