CREATE PROCEDURE PROCEDURE_NAME
    IS
    v_new_pages NUMBER;
    v_title VARCHAR2(100);
BEGIN
    UPDATE "HR"."BOOKS"
        SET "PAGE_COUNT" = "PAGE_COUNT" + 20
        WHERE "PAGE_COUNT" > 800
    RETURNING "PAGE_COUNT", "TITLE" INTO v_new_pages, v_title;
END;

CREATE PROCEDURE PROCEDURE_NAME1
    IS
    v_new_pages1 NUMBER;
    v_title1 VARCHAR2(100);
BEGIN
    UPDATE "HR"."BOOKS"
        SET "PAGE_COUNT" = "PAGE_COUNT" + 20
        WHERE "PAGE_COUNT" > 800
    RETURN "PAGE_COUNT", "TITLE" INTO v_new_pages1, v_title1;
END;