--V_CITY POPULATION
CREATE GLOBAL TEMPORARY TABLE V_CITY (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_V_CITY PRIMARY KEY (K)
);


EXECUTE BLOCK 
 AS 


    --TYPE POPULATION IS TABLE OF NUMERIC(34, 8) INDEX BY VARCHAR(64);

    --v_city  POPULATION;
     DECLARE I  VARCHAR(64);
     DECLARE VAL NUMERIC(34, 8);

BEGIN
    VAL = (SELECT VAL FROM V_CITY WHERE K = :I);
    I = (SELECT FIRST 1 K FROM V_CITY ORDER BY K DESC);
    I = (SELECT FIRST 1 K FROM V_CITY ORDER BY K ASC);
    I = (SELECT FIRST 1 K FROM V_CITY WHERE K > :I ORDER BY K ASC);
    I = (SELECT COUNT(*) FROM V_CITY);
    I = (SELECT FIRST 1 K FROM V_CITY WHERE K < 'MIDLAND' ORDER BY K DESC);
    bool_val = (SELECT COUNT(*) > 0 FROM V_CITY WHERE K = 'MIDLAND');
    DELETE FROM V_CITY WHERE K = 'MIDLAND';
    DELETE FROM V_CITY WHERE K >= 'COLUMBUS' AND K <= 'SAN DIEGO' ORDER BY K;
    DELETE FROM V_CITY;
END;