DECLARE
    TYPE FOURSOME IS VARRAY(4) OF VARCHAR2(15);

    TEAM FOURSOME := FOURSOME('JOHN', 'MARY', 'ALBERTO', 'JUANITA');
    NUMELEMENTS INTEGER;
    ELEMENTEXISTS BOOLEAN;
    FIRSTELEMENT VARCHAR2(100);
    LASTELEMENT VARCHAR2(100);
    LIMITVAR VARCHAR2(100);
    I NUMBER;
BEGIN
    NUMELEMENTS := TEAM.COUNT;
    -- EXTEND
    TEAM.EXTEND; -- INCREASES THE COLLECTION SIZE (CAN BE REMOVED DURING CONVERSION)
    -- GET ELEMENT BY ID (2)
    FIRSTELEMENT := TEAM(2);
    -- ACCESS THE FIRST ELEMENT OF THE VARRAY DIRECTLY USING INDEX 1
    FIRSTELEMENT := TEAM(TEAM.FIRST);
    -- ACCESS THE LAST ELEMENT OF THE VARRAY USING THE COUNT METHOD TO DETERMINE THE NUMBER OF ELEMENTS
    LASTELEMENT := TEAM(TEAM.LAST);
    -- DELETE (DELETE ALL ELEMENTS FROM VARRAY)
    TEAM.DELETE();
    -- DELETE LAST ELEMENT OF VARRAY
    TEAM.TRIM;
    -- TRIM(N) - DELETE LAST N ELEMENTS OF VARRAY
    TEAM.TRIM(2);
    -- ONLY VARRAY HAVE LIMIT
    LIMITVAR := TEAM.LIMIT;
    -- EXISTS IS A FUNCTION THAT TELLS YOU WHETHER THE SPECIFIED ELEMENT OF A VARRAY OR NESTED TABLE EXISTS.
    ELEMENTEXISTS := TEAM.EXISTS(2); -- checks if the second element exists
    I := TEAM.NEXT; -- returns the index of the next element
    I := TEAM.PRIOR; -- returns the index of the previous element
END;