/*SELECT [-unconvertible RS-245858 EXTRACT(YEAR FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(month FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(day FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(HOUR FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(MINUTE FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(second FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(TIMEZONE_HOUR FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(TIMEZONE_MINUTE FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(TIMEZONE_ABBR FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(TIMEZONE_REGION FROM CURRENT_TIMESTAMP)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(HOUR FROM TIMESTAMP '1999-01-01 10:00:00 -08:00')] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(YEAR FROM INTERVAL '123-06' YEAR(3) TO MONTH)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(month FROM INTERVAL '123-06' YEAR(3) TO MONTH)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245858 EXTRACT(day FROM INTERVAL '1 3' DAY(3) TO HOUR)] FROM RDB$DATABASE;*/