/*SELECT [-unconvertible RS-245838 DECOMPOSE ('Chateaux')] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245838 DECOMPOSE ('Chateaux', 'CANONICAL')] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245838 DECOMPOSE ('Chateaux', 'COMPATIBILITY')] FROM RDB$DATABASE;*/