/*SELECT [-unconvertible RS-245838 DECOMPOSE ('Châteaux')] FROM RDB$DATABASE;*/ 

/*SELECT [-unconvertible RS-245838 DECOMPOSE ('Châteaux', 'CANONICAL')] FROM RDB$DATABASE;*/ 

/*SELECT [-unconvertible RS-245838 DECOMPOSE ('Châteaux', 'COMPATIBILITY')] FROM RDB$DATABASE;*/ 