CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

EXECUTE BLOCK
 AS
   DECLARE p1 BINARY(56) = 'hello';
   DECLARE p2  BLOB = 'world';
   DECLARE res BLOB;
BEGIN
  select CAST(:p1 AS BLOB)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p2 AS BLOB)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
END;