CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

EXECUTE BLOCK
 AS

/*
   DECLARE p1 [-unconvertible RS-244046 INTERVAL DAY TO SECOND] = INTERVAL '1' DAY;
   DECLARE p2 [-unconvertible RS-244046 INTERVAL YEAR TO MONTH] = interval '10' year;
   DECLARE res VARCHAR(100);
*/
BEGIN
/*
  select CAST(:p1)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS VARCHAR(32765) FORMAT  'DD')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS VARCHAR(32765) FORMAT  'DD' )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p2)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS VARCHAR(32765) FORMAT  'YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS VARCHAR(32765) FORMAT  'YYYY' )
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
*/
END;