CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

EXECUTE BLOCK
 AS

   DECLARE p1 TIMESTAMP =  date '2011-11-03';
   DECLARE p2 TIMESTAMP = LOCALTIMESTAMP;
   DECLARE p3 TIMESTAMP WITH TIME ZONE = CURRENT_TIMESTAMP;
   DECLARE res VARCHAR(100);
BEGIN
  select CAST(:p1 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS VARCHAR FORMAT 'DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p1 AS VARCHAR FORMAT 'DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p2 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS VARCHAR FORMAT 'HH24:MI:SS.FF9 DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p2 AS VARCHAR FORMAT 'HH24:MI:SS.FF9 DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p3 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p3 AS VARCHAR FORMAT 'HH24:MI:SS.FF9 DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p3 AS VARCHAR FORMAT 'HH24:MI:SS.FF9 DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
END;

EXECUTE BLOCK
 AS

/*
   DECLARE p4 [-unconvertible RS-244046 TIMESTAMP WITH LOCAL TIME ZONE] = timestamp '2020-10-25 02:30:00+02:00';
   DECLARE res VARCHAR(100);
*/
BEGIN
/*
  select CAST(:p4 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p4 AS VARCHAR FORMAT 'DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
  select CAST(:p4 AS VARCHAR FORMAT 'DD-MON-YYYY')
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
*/
END;