CREATE EXCEPTION NO_DATA_FOUND
	'no data found';

EXECUTE BLOCK
 AS

   DECLARE p1 CHAR(10) = 'hello';
   DECLARE p2 VARCHAR(10) = 'world';
   DECLARE p3 BLOB SUB_TYPE TEXT = 'hello';
   DECLARE p4 BLOB SUB_TYPE TEXT = 'world';
   DECLARE res VARCHAR(100);
BEGIN
  select CAST(:p1 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p2 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p3 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;

  select CAST(:p4 AS VARCHAR)
  from RDB$DATABASE
  into :res;
  IF (ROW_COUNT = 0) THEN
  	EXCEPTION NO_DATA_FOUND;
END;