SELECT CAST(CAST('2025-04-23'  AS TIMESTAMP FORMAT 'YYYY-MM-DD') AS DATE)  FROM RDB$DATABASE;

SELECT CAST(CAST('February 15, 2016, 11:00 A.M.'
        AS TIMESTAMP FORMAT 'Month dd, YYYY, HH:MI A.M.') AS DATE)  FROM RDB$DATABASE;

SELECT CAST(CAST('January 15, 1989, 11:00 A.M.'
     AS TIMESTAMP FORMAT 'Month dd, YYYY, HH:MI A.M.'
    ) AS DATE)  FROM RDB$DATABASE;
SELECT CAST(CAST('January 15, 1989, 11:00 A.M.'
     AS TIMESTAMP FORMAT 'Month dd, YYYY, HH:MI A.M.'
    ) AS DATE)  FROM RDB$DATABASE;