CREATE PROCEDURE PROCEDURE_NAME (in_p VARCHAR)
 SQL SECURITY DEFINER
 AS
BEGIN

END;

CREATE PROCEDURE CALLING_PROCEDURE_NAME
     SQL SECURITY DEFINER
 AS
     DECLARE in_value VARCHAR(50);
BEGIN
    in_value = 'in_value';
    EXECUTE PROCEDURE PROCEDURE_NAME(:in_value);
END;