CREATE PROCEDURE PROCEDURE_NAME (in_p VARCHAR)
IS
BEGIN
    NULL;
END;

CREATE FUNCTION CALLING_FUNCTION_NAME
RETURN VARCHAR2
    IS
    in_value VARCHAR2(50);
BEGIN
    in_value := 'in_value';
    PROCEDURE_NAME(in_value);
END;
