/*CREATE FUNCTION FDELETE (
   FILE VARCHAR(32765)) RETURNS NUMERIC(34, 8)
SQL SECURITY DEFINER
AS [-unconvertible RS-239602 LANGUAGE JAVA
      NAME 'JDelete.delete (java.lang.String) return int'];*/