/*CREATE FUNCTION SHELL(CMD VARCHAR)
RETURNS INTEGER
SQL SECURITY DEFINER
AS
[-unconvertible RS-239602 LANGUAGE C
LIBRARY EXTPROCSHELL_LIB
NAME "EXTPROCSHELL"
PARAMETERS (:CMD STRING, RETURN INT)];*/

/*CREATE FUNCTION SHELL(CMD VARCHAR)
    RETURNS INTEGER
SQL SECURITY DEFINER
AS
[-unconvertible RS-239602 EXTERNAL                       -- using external clause
LIBRARY EXTPROCSHELL_LIB
NAME "EXTPROCSHELL"
PARAMETERS (:CMD STRING, RETURN INT)];*/