/*CREATE OR ALTER PACKAGE MY_TYPES  SQL SECURITY DEFINER
AS BEGIN
    --TYPE MY_AA IS TABLE OF VARCHAR(20) INDEX BY INTEGER;
    --[-unconvertible RS-246002 v_my_aa MY_AA;]
  END;*/



RECREATE   PACKAGE BODY MY_TYPES AS BEGIN

  END;