CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_F (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_F PRIMARY KEY (K)
);

CREATE FUNCTION FUNCTION_NAME
RETURNS VARCHAR(32765)
SQL SECURITY DEFINER
AS
/*TYPE POPULATION IS TABLE OF NUMERIC(34, 8)
    INDEX BY VARCHAR(64);*/

    /*CITY_POPULATION_F  POPULATION;*/
BEGIN

END;