--CITY_POPULATION_N_F POPULATION
CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_N_F (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_N_F PRIMARY KEY (K)
);


CREATE FUNCTION FUNCTION_NAME
RETURNS VARCHAR(32765)

 SQL SECURITY DEFINER
 AS
    DECLARE FUNCTION NESTED_FUNCTION_NAME
    RETURNS VARCHAR(32765)
    AS
        --TYPE POPULATION IS TABLE OF NUMERIC(34, 8) INDEX BY VARCHAR(64);
        --CITY_POPULATION_N_F  POPULATION;
    BEGIN

    END
BEGIN

END;