CREATE FUNCTION FUNCTION_NAME
RETURN VARCHAR2
IS
    FUNCTION NESTED_FUNCTION_NAME
    RETURN VARCHAR2
    IS
        TYPE POPULATION IS TABLE OF NUMBER
        INDEX BY VARCHAR2(64);

        CITY_POPULATION_N_F  POPULATION;
    BEGIN
        NULL;
    END;
BEGIN
    NULL;
END;
