CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_T (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_T PRIMARY KEY (K)
);

CREATE TRIGGER TRIGGER_NAME
BEFORE INSERT ON EMPLOYEES
SQL SECURITY DEFINER
AS
/*TYPE POPULATION IS TABLE OF NUMERIC(34, 8)
    INDEX BY VARCHAR(64);*/

    /*CITY_POPULATION_T  POPULATION;*/
BEGIN

END;