CREATE PROCEDURE PROCEDURE_NAME
IS
    PROCEDURE NESTED_PROCEDURE_NAME
    IS
        TYPE POPULATION IS TABLE OF NUMBER
        INDEX BY VARCHAR2(64);

        CITY_POPULATION_N_P  POPULATION;
    BEGIN
        NULL;
    END;

BEGIN
    NULL;
END;
