CREATE PACKAGE PACKAGE_NAME
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME RETURNS VARCHAR(32765);
END /*PACKAGE_NAME*/;

CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_P_F (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_P_F PRIMARY KEY (K)
);

CREATE PACKAGE BODY PACKAGE_NAME
AS BEGIN
   FUNCTION FUNCTION_NAME
   RETURNS VARCHAR(32765)
   AS
   /*TYPE POPULATION IS TABLE OF NUMERIC(34, 8)
    INDEX BY VARCHAR(64);*/

    /*CITY_POPULATION_P_F  POPULATION;*/
   BEGIN

   END
END /*PACKAGE_NAME*/;