CREATE PACKAGE PACKAGE_NAME
AS
   FUNCTION FUNCTION_NAME RETURN VARCHAR2;
END PACKAGE_NAME;

CREATE PACKAGE BODY PACKAGE_NAME
AS
   FUNCTION FUNCTION_NAME
   RETURN VARCHAR2
   IS
    TYPE POPULATION IS TABLE OF NUMBER
        INDEX BY VARCHAR2(64);

        CITY_POPULATION_P_F  POPULATION;
   BEGIN
        NULL;
   END;
END PACKAGE_NAME;
