CREATE PACKAGE PACKAGE_NAME
AS
    PROCEDURE PROCEDURE_NAME;
END PACKAGE_NAME;

CREATE PACKAGE BODY PACKAGE_NAME
AS
    PROCEDURE PROCEDURE_NAME
    IS
    TYPE POPULATION IS TABLE OF NUMBER
        INDEX BY VARCHAR2(64);

    CITY_POPULATION_P_P  POPULATION;
    BEGIN
        NULL;
    END;
END PACKAGE_NAME;