CREATE PACKAGE PACKAGE_NAME
SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PROCEDURE_NAME;
  END ;
--CITY_POPULATION_P_P POPULATION
CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_P_P (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_P_P PRIMARY KEY (K)
);


CREATE PACKAGE BODY PACKAGE_NAME
AS BEGIN
    PROCEDURE PROCEDURE_NAME
    AS
        --TYPE POPULATION IS TABLE OF NUMERIC(34, 8) INDEX BY VARCHAR(64);
        --CITY_POPULATION_P_P  POPULATION;
    BEGIN

    END
  END ;