--CITY_POPULATION_N_P POPULATION
CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_N_P (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_N_P PRIMARY KEY (K)
);


CREATE PROCEDURE PROCEDURE_NAME

 SQL SECURITY DEFINER
 AS
   DECLARE PROCEDURE NESTED_PROCEDURE_NAME
    AS
        --TYPE POPULATION IS TABLE OF NUMERIC(34, 8) INDEX BY VARCHAR(64);
        --CITY_POPULATION_N_P  POPULATION;
    BEGIN

    END

BEGIN

END;