CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION_A_N (
	K VARCHAR(64),
	VAL NUMERIC(34, 8),
	CONSTRAINT PK_CITY_POPULATION_A_N PRIMARY KEY (K)
);


EXECUTE BLOCK
 AS

/*TYPE POPULATION IS TABLE OF NUMERIC(34, 8)
    INDEX BY VARCHAR(64);*/

    /*CITY_POPULATION_A_N  POPULATION;*/

    BEGIN

END;