SELECT POSITION('CORPORATE FLOOR','OR', 3, 2) FROM RDB$DATABASE;

SELECT POSITION('CORPORATE FLOOR','OR') FROM RDB$DATABASE;

SELECT POSITION('CORPORATE FLOOR','IR') FROM RDB$DATABASE;

SELECT POSITION('CORPORATE FLOOR','OR', 3) FROM RDB$DATABASE;

SELECT POSITION('CORPORATE FLOOR','OR', 3, 20) FROM RDB$DATABASE;

SELECT POSITION('CORPORATE FLOOR','OR', 30, 2) FROM RDB$DATABASE;

/*SELECT POSITION('CORPORATE FLOOR','OR', [-unconvertible RS-245294 -3]) FROM RDB$DATABASE;*/

/*SELECT POSITION('CORPORATE FLOOR','OR', [-unconvertible RS-245294 -1]) FROM RDB$DATABASE;*/

/*SELECT POSITION('CORPORATE FLOOR','OR', [-unconvertible RS-245294 -1], 2) FROM RDB$DATABASE;*/

/*SELECT POSITION('CORPORATE FLOOR','OR', [-unconvertible RS-245294 -1], 3) FROM RDB$DATABASE;*/


/*SELECT [-unconvertible RS-245294 INSTRB('CORPORATE FLOOR','OR', [-unconvertible RS-245294 -3], 2)] FROM RDB$DATABASE;*/
/*SELECT [-unconvertible RS-245294 INSTRC('CORPORATE FLOOR','OR', 3, 2)] FROM RDB$DATABASE;*/
/*SELECT [-unconvertible RS-245294 INSTR2('CORPORATE FLOOR','OR', 3, 2)] FROM RDB$DATABASE;*/
/*SELECT [-unconvertible RS-245294 INSTR4('CORPORATE FLOOR','OR', 3, 2)] FROM RDB$DATABASE;*/