SELECT LENGTH('CANDIDE') FROM DUAL;
SELECT LENGTH('hand') FROM DUAL;
SELECT LENGTH('') FROM DUAL;

SELECT LENGTHB('CANDIDE') FROM DUAL;
SELECT LENGTHB('hand') FROM DUAL;
SELECT LENGTHB('') FROM DUAL;


SELECT LENGTHC('CANDIDE') FROM DUAL;
SELECT LENGTH2('CANDIDE') FROM DUAL;
SELECT LENGTH4('CANDIDE') FROM DUAL;