SELECT DECODE('CANDIDE', '', NULL, CHAR_LENGTH('CANDIDE')) FROM RDB$DATABASE;
SELECT DECODE('hand', '', NULL, CHAR_LENGTH('hand')) FROM RDB$DATABASE;
SELECT DECODE('', '', NULL, CHAR_LENGTH('')) FROM RDB$DATABASE;

SELECT DECODE('CANDIDE', '', NULL, OCTET_LENGTH('CANDIDE')) FROM RDB$DATABASE;
SELECT DECODE('hand', '', NULL, OCTET_LENGTH('hand')) FROM RDB$DATABASE;
SELECT DECODE('', '', NULL, OCTET_LENGTH('')) FROM RDB$DATABASE;


/*SELECT [-unconvertible RS-245294 LENGTHC('CANDIDE')] FROM RDB$DATABASE;*/
/*SELECT [-unconvertible RS-245294 LENGTH2('CANDIDE')] FROM RDB$DATABASE;*/
/*SELECT [-unconvertible RS-245294 LENGTH4('CANDIDE')] FROM RDB$DATABASE;*/