SELECT SUBSTRING('ABCDEFGHIJK' FROM 3) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM 3 FOR 4) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM 3 FOR 0) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM -5) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM -5 FOR 4) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM -5 FOR 0) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM 0) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM 0 FOR 4) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM 3 FOR 100) FROM RDB$DATABASE;

SELECT SUBSTRING('' FROM 3) FROM RDB$DATABASE;

SELECT SUBSTRING('ABCDEFGHIJK' FROM -50) FROM RDB$DATABASE;

/*SELECT [-unconvertible RS-245294 SUBSTRB('ABCDEFG',5,4)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245294 SUBSTRC('ABCDEFG',5,4)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245294 SUBSTR2('ABCDEFG',5,4)] FROM RDB$DATABASE;*/

/*SELECT [-unconvertible RS-245294 SUBSTR4('ABCDEFG',5,4)] FROM RDB$DATABASE;*/