CREATE PACKAGE PackF_Exit_When
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Exit_When
   RETURNS VARCHAR(32765);
  END;

CREATE PACKAGE BODY PackF_Exit_When
AS BEGIN
   FUNCTION PF_Exit_When
   RETURNS VARCHAR(32765)
   AS
     DECLARE VARIABLE i INTEGER;
   BEGIN
     i = 1;
     WHILE ( i <= 3) DO
     BEGIN
       IF( :i = 3 ) THEN
       	LEAVE  ;
     i = i + 1;
     END
     RETURN '';
   END
END;