
CREATE OR ALTER FUNCTION CALL_F
RETURNS BOOLEAN
 SQL SECURITY DEFINER
 AS
/*
     DECLARE VALUE_OUT NUMERIC(34, 8);
     DECLARE STMT VARCHAR(50);
*/
BEGIN
/*
    VALUE_OUT = 0;
    STMT = 'BEGIN OUT_P(:A); END;';
    EXECUTE STATEMENT (:STMT) [-unconvertible RS-245747 USING  OUT :VALUE_OUT];
    RETURN TRUE;
*/
END;